apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - "config/postgres-db-init.yaml"
  - "deploy/postgres-service.yaml"
  - "deploy/postgres-pv-claim.yaml"
  - "secret/postgres-secret.yaml"
  - "deploy/postgres-deployment.yaml"
